webtalk_init -webtalk_dir C:\\Projects\\kyber-fpga\\kyber-fpga.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2021-05-09 16:59:05" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5e5nfel1a2qpm5q7atrpu5ascm" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_14" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4702HQ CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2195 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.078 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1620587599540" -context "sdk\\\\bsp/1620587599540"
webtalk_add_data -client sdk -key hwid -value "1612564186027" -context "sdk\\\\bsp/1620587599540"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1620587599540"
webtalk_add_data -client sdk -key apptemplate -value "lwip_tcp_perf_server" -context "sdk\\\\bsp/1620587599540"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1620587599540"
webtalk_add_data -client sdk -key uid -value "1620587610055" -context "sdk\\\\application/1620587610055"
webtalk_add_data -client sdk -key hwid -value "1612564186027" -context "sdk\\\\application/1620587610055"
webtalk_add_data -client sdk -key bspid -value "1620587599540" -context "sdk\\\\application/1620587610055"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1620587610055"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1620587610055"
webtalk_add_data -client sdk -key apptemplate -value "lwip_tcp_perf_server" -context "sdk\\\\application/1620587610055"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1620587610055"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1620587610055"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1620587610055"
webtalk_add_data -client sdk -key projSize -value "1102.28515625" -context "sdk\\\\application/1620587610055"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1620590345479"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1620590345479"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1620590345479"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1620590345479"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1620590345479"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1620590345479"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1620590345479"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1620590345479"
webtalk_transmit -clientid 1164098251 -regid "" -xml C:\\Projects\\kyber-fpga\\kyber-fpga.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Projects\\kyber-fpga\\kyber-fpga.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Projects\\kyber-fpga\\kyber-fpga.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
