# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/kyberBD/kyberBD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD || ORIG_REF_NAME==kyberBD} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_processing_system7_0_0/kyberBD_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_processing_system7_0_0 || ORIG_REF_NAME==kyberBD_processing_system7_0_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_proc_sys_reset_0_0/kyberBD_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_proc_sys_reset_0_0 || ORIG_REF_NAME==kyberBD_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_xbar_0/kyberBD_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_xbar_0 || ORIG_REF_NAME==kyberBD_xbar_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_axi_interconnect_0_0/kyberBD_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_axi_interconnect_0_0 || ORIG_REF_NAME==kyberBD_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_axi_gpio_0_0/kyberBD_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_0_0 || ORIG_REF_NAME==kyberBD_axi_gpio_0_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_timer2_0_0/kyberBD_timer2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_timer2_0_0 || ORIG_REF_NAME==kyberBD_timer2_0_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_axi_gpio_1_0/kyberBD_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_1_0 || ORIG_REF_NAME==kyberBD_axi_gpio_1_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_bram_port_selector_0_0/kyberBD_bram_port_selector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_bram_port_selector_0_0 || ORIG_REF_NAME==kyberBD_bram_port_selector_0_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_poly_tomont_0_0/kyberBD_poly_tomont_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_poly_tomont_0_0 || ORIG_REF_NAME==kyberBD_poly_tomont_0_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_bram_port_selector_1_0/kyberBD_bram_port_selector_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_bram_port_selector_1_0 || ORIG_REF_NAME==kyberBD_bram_port_selector_1_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_axi_gpio_2_0/kyberBD_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_2_0 || ORIG_REF_NAME==kyberBD_axi_gpio_2_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_polyvec_reduce_0_0/kyberBD_polyvec_reduce_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_polyvec_reduce_0_0 || ORIG_REF_NAME==kyberBD_polyvec_reduce_0_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_bram_port_selector_2_0/kyberBD_bram_port_selector_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_bram_port_selector_2_0 || ORIG_REF_NAME==kyberBD_bram_port_selector_2_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_polyvec_basemul_acc_0_1/kyberBD_polyvec_basemul_acc_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_polyvec_basemul_acc_0_1 || ORIG_REF_NAME==kyberBD_polyvec_basemul_acc_0_1} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_axi_gpio_3_0/kyberBD_axi_gpio_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_3_0 || ORIG_REF_NAME==kyberBD_axi_gpio_3_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_bram_port_selector_1_1/kyberBD_bram_port_selector_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_bram_port_selector_1_1 || ORIG_REF_NAME==kyberBD_bram_port_selector_1_1} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_fqmul_0_0/kyberBD_fqmul_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_fqmul_0_0 || ORIG_REF_NAME==kyberBD_fqmul_0_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_fqmul_0_1/kyberBD_fqmul_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_fqmul_0_1 || ORIG_REF_NAME==kyberBD_fqmul_0_1} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_fqmul_0_2/kyberBD_fqmul_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_fqmul_0_2 || ORIG_REF_NAME==kyberBD_fqmul_0_2} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_fqmul_0_3/kyberBD_fqmul_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_fqmul_0_3 || ORIG_REF_NAME==kyberBD_fqmul_0_3} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_fqmul_0_4/kyberBD_fqmul_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_fqmul_0_4 || ORIG_REF_NAME==kyberBD_fqmul_0_4} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_fqmul_0_5/kyberBD_fqmul_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_fqmul_0_5 || ORIG_REF_NAME==kyberBD_fqmul_0_5} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_montgomery_reduction_0_0/kyberBD_montgomery_reduction_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_montgomery_reduction_0_0 || ORIG_REF_NAME==kyberBD_montgomery_reduction_0_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_montgomery_reduction_0_1/kyberBD_montgomery_reduction_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_montgomery_reduction_0_1 || ORIG_REF_NAME==kyberBD_montgomery_reduction_0_1} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_montgomery_reduction_0_2/kyberBD_montgomery_reduction_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_montgomery_reduction_0_2 || ORIG_REF_NAME==kyberBD_montgomery_reduction_0_2} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_montgomery_reduction_0_3/kyberBD_montgomery_reduction_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_montgomery_reduction_0_3 || ORIG_REF_NAME==kyberBD_montgomery_reduction_0_3} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_montgomery_reduction_0_4/kyberBD_montgomery_reduction_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_montgomery_reduction_0_4 || ORIG_REF_NAME==kyberBD_montgomery_reduction_0_4} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_montgomery_reduction_0_5/kyberBD_montgomery_reduction_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_montgomery_reduction_0_5 || ORIG_REF_NAME==kyberBD_montgomery_reduction_0_5} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_barrett_reduce_0_0/kyberBD_barrett_reduce_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_barrett_reduce_0_0 || ORIG_REF_NAME==kyberBD_barrett_reduce_0_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_barrett_reduce_0_1/kyberBD_barrett_reduce_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_barrett_reduce_0_1 || ORIG_REF_NAME==kyberBD_barrett_reduce_0_1} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_polyvec_ntt_0_0/kyberBD_polyvec_ntt_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_polyvec_ntt_0_0 || ORIG_REF_NAME==kyberBD_polyvec_ntt_0_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_axi_gpio_4_0/kyberBD_axi_gpio_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_4_0 || ORIG_REF_NAME==kyberBD_axi_gpio_4_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_signal_multiplexer_0_0/kyberBD_signal_multiplexer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_signal_multiplexer_0_0 || ORIG_REF_NAME==kyberBD_signal_multiplexer_0_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_signal_multiplexer_0_1/kyberBD_signal_multiplexer_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_signal_multiplexer_0_1 || ORIG_REF_NAME==kyberBD_signal_multiplexer_0_1} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_signal_multiplexer_2_0/kyberBD_signal_multiplexer_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_signal_multiplexer_2_0 || ORIG_REF_NAME==kyberBD_signal_multiplexer_2_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_signal_multiplexer_2_1/kyberBD_signal_multiplexer_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_signal_multiplexer_2_1 || ORIG_REF_NAME==kyberBD_signal_multiplexer_2_1} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_signal_multiplexer_2_2/kyberBD_signal_multiplexer_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_signal_multiplexer_2_2 || ORIG_REF_NAME==kyberBD_signal_multiplexer_2_2} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_signal_multiplexer_2_3/kyberBD_signal_multiplexer_2_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_signal_multiplexer_2_3 || ORIG_REF_NAME==kyberBD_signal_multiplexer_2_3} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_signal_multiplexer_2_4/kyberBD_signal_multiplexer_2_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_signal_multiplexer_2_4 || ORIG_REF_NAME==kyberBD_signal_multiplexer_2_4} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_signal_multiplexer_2_5/kyberBD_signal_multiplexer_2_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_signal_multiplexer_2_5 || ORIG_REF_NAME==kyberBD_signal_multiplexer_2_5} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_signal_multiplexer_12_0/kyberBD_signal_multiplexer_12_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_signal_multiplexer_12_0 || ORIG_REF_NAME==kyberBD_signal_multiplexer_12_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_signal_multiplexer_12_2/kyberBD_signal_multiplexer_12_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_signal_multiplexer_12_2 || ORIG_REF_NAME==kyberBD_signal_multiplexer_12_2} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_signal_multiplexer_12_4/kyberBD_signal_multiplexer_12_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_signal_multiplexer_12_4 || ORIG_REF_NAME==kyberBD_signal_multiplexer_12_4} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_signal_multiplexer_16_0/kyberBD_signal_multiplexer_16_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_signal_multiplexer_16_0 || ORIG_REF_NAME==kyberBD_signal_multiplexer_16_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_signal_multiplexer_17_0/kyberBD_signal_multiplexer_17_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_signal_multiplexer_17_0 || ORIG_REF_NAME==kyberBD_signal_multiplexer_17_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_signal_multiplexer_17_1/kyberBD_signal_multiplexer_17_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_signal_multiplexer_17_1 || ORIG_REF_NAME==kyberBD_signal_multiplexer_17_1} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_polyvec_invntt_0_0/kyberBD_polyvec_invntt_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_polyvec_invntt_0_0 || ORIG_REF_NAME==kyberBD_polyvec_invntt_0_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_keccak_f1600_bram_ip_0_0/kyberBD_keccak_f1600_bram_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_keccak_f1600_bram_ip_0_0 || ORIG_REF_NAME==kyberBD_keccak_f1600_bram_ip_0_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_axi_dma_0_0/kyberBD_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_axi_dma_0_0 || ORIG_REF_NAME==kyberBD_axi_dma_0_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_dual_bram_axis_0_1/kyberBD_dual_bram_axis_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_dual_bram_axis_0_1 || ORIG_REF_NAME==kyberBD_dual_bram_axis_0_1} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_xlconcat_0_0/kyberBD_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_xlconcat_0_0 || ORIG_REF_NAME==kyberBD_xlconcat_0_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_axi_gpio_5_0/kyberBD_axi_gpio_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_5_0 || ORIG_REF_NAME==kyberBD_axi_gpio_5_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_timer_0_1/kyberBD_timer_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_timer_0_1 || ORIG_REF_NAME==kyberBD_timer_0_1} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_timer_0_2/kyberBD_timer_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_timer_0_2 || ORIG_REF_NAME==kyberBD_timer_0_2} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_timer_0_3/kyberBD_timer_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_timer_0_3 || ORIG_REF_NAME==kyberBD_timer_0_3} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_timer_0_4/kyberBD_timer_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_timer_0_4 || ORIG_REF_NAME==kyberBD_timer_0_4} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_timer_0_5/kyberBD_timer_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_timer_0_5 || ORIG_REF_NAME==kyberBD_timer_0_5} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_timer_0_6/kyberBD_timer_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_timer_0_6 || ORIG_REF_NAME==kyberBD_timer_0_6} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_axi_gpio_6_0/kyberBD_axi_gpio_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_6_0 || ORIG_REF_NAME==kyberBD_axi_gpio_6_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_xbar_1/kyberBD_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_xbar_1 || ORIG_REF_NAME==kyberBD_xbar_1} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_axi_interconnect_1_0/kyberBD_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_axi_interconnect_1_0 || ORIG_REF_NAME==kyberBD_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_axi_gpio_6_2/kyberBD_axi_gpio_6_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_6_2 || ORIG_REF_NAME==kyberBD_axi_gpio_6_2} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_axi_gpio_6_3/kyberBD_axi_gpio_6_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_6_3 || ORIG_REF_NAME==kyberBD_axi_gpio_6_3} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_axi_gpio_6_4/kyberBD_axi_gpio_6_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_6_4 || ORIG_REF_NAME==kyberBD_axi_gpio_6_4} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_axi_gpio_6_5/kyberBD_axi_gpio_6_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_6_5 || ORIG_REF_NAME==kyberBD_axi_gpio_6_5} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_axi_gpio_6_6/kyberBD_axi_gpio_6_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_6_6 || ORIG_REF_NAME==kyberBD_axi_gpio_6_6} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_auto_pc_0/kyberBD_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_auto_pc_0 || ORIG_REF_NAME==kyberBD_auto_pc_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_auto_pc_1_1/kyberBD_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_auto_pc_1 || ORIG_REF_NAME==kyberBD_auto_pc_1} -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_processing_system7_0_0/kyberBD_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_processing_system7_0_0 || ORIG_REF_NAME==kyberBD_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_proc_sys_reset_0_0/kyberBD_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_proc_sys_reset_0_0 || ORIG_REF_NAME==kyberBD_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_proc_sys_reset_0_0/kyberBD_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_proc_sys_reset_0_0 || ORIG_REF_NAME==kyberBD_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_proc_sys_reset_0_0/kyberBD_proc_sys_reset_0_0_ooc.xdc

# XDC: bd/kyberBD/ip/kyberBD_xbar_0/kyberBD_xbar_0_ooc.xdc

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_0_0/kyberBD_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_0_0 || ORIG_REF_NAME==kyberBD_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_0_0/kyberBD_axi_gpio_0_0_ooc.xdc

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_0_0/kyberBD_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_0_0 || ORIG_REF_NAME==kyberBD_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_1_0/kyberBD_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_1_0 || ORIG_REF_NAME==kyberBD_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_1_0/kyberBD_axi_gpio_1_0_ooc.xdc

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_1_0/kyberBD_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_1_0 || ORIG_REF_NAME==kyberBD_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_2_0/kyberBD_axi_gpio_2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_2_0 || ORIG_REF_NAME==kyberBD_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_2_0/kyberBD_axi_gpio_2_0_ooc.xdc

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_2_0/kyberBD_axi_gpio_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_2_0 || ORIG_REF_NAME==kyberBD_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_3_0/kyberBD_axi_gpio_3_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_3_0 || ORIG_REF_NAME==kyberBD_axi_gpio_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_3_0/kyberBD_axi_gpio_3_0_ooc.xdc

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_3_0/kyberBD_axi_gpio_3_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_3_0 || ORIG_REF_NAME==kyberBD_axi_gpio_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_4_0/kyberBD_axi_gpio_4_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_4_0 || ORIG_REF_NAME==kyberBD_axi_gpio_4_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_4_0/kyberBD_axi_gpio_4_0_ooc.xdc

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_4_0/kyberBD_axi_gpio_4_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_4_0 || ORIG_REF_NAME==kyberBD_axi_gpio_4_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_axi_dma_0_0/kyberBD_axi_dma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_axi_dma_0_0 || ORIG_REF_NAME==kyberBD_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_axi_dma_0_0/kyberBD_axi_dma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_axi_dma_0_0 || ORIG_REF_NAME==kyberBD_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_axi_dma_0_0/kyberBD_axi_dma_0_0_ooc.xdc

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_5_0/kyberBD_axi_gpio_5_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_5_0 || ORIG_REF_NAME==kyberBD_axi_gpio_5_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_5_0/kyberBD_axi_gpio_5_0_ooc.xdc

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_5_0/kyberBD_axi_gpio_5_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_5_0 || ORIG_REF_NAME==kyberBD_axi_gpio_5_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_6_0/kyberBD_axi_gpio_6_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_6_0 || ORIG_REF_NAME==kyberBD_axi_gpio_6_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_6_0/kyberBD_axi_gpio_6_0_ooc.xdc

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_6_0/kyberBD_axi_gpio_6_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_6_0 || ORIG_REF_NAME==kyberBD_axi_gpio_6_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_xbar_1/kyberBD_xbar_1_ooc.xdc

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_6_2/kyberBD_axi_gpio_6_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_6_2 || ORIG_REF_NAME==kyberBD_axi_gpio_6_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_6_2/kyberBD_axi_gpio_6_2_ooc.xdc

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_6_2/kyberBD_axi_gpio_6_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_6_2 || ORIG_REF_NAME==kyberBD_axi_gpio_6_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_6_3/kyberBD_axi_gpio_6_3_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_6_3 || ORIG_REF_NAME==kyberBD_axi_gpio_6_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_6_3/kyberBD_axi_gpio_6_3_ooc.xdc

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_6_3/kyberBD_axi_gpio_6_3.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_6_3 || ORIG_REF_NAME==kyberBD_axi_gpio_6_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_6_4/kyberBD_axi_gpio_6_4_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_6_4 || ORIG_REF_NAME==kyberBD_axi_gpio_6_4} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_6_4/kyberBD_axi_gpio_6_4_ooc.xdc

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_6_4/kyberBD_axi_gpio_6_4.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_6_4 || ORIG_REF_NAME==kyberBD_axi_gpio_6_4} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_6_5/kyberBD_axi_gpio_6_5_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_6_5 || ORIG_REF_NAME==kyberBD_axi_gpio_6_5} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_6_5/kyberBD_axi_gpio_6_5_ooc.xdc

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_6_5/kyberBD_axi_gpio_6_5.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_6_5 || ORIG_REF_NAME==kyberBD_axi_gpio_6_5} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_6_6/kyberBD_axi_gpio_6_6_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_6_6 || ORIG_REF_NAME==kyberBD_axi_gpio_6_6} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_6_6/kyberBD_axi_gpio_6_6_ooc.xdc

# XDC: bd/kyberBD/ip/kyberBD_axi_gpio_6_6/kyberBD_axi_gpio_6_6.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_axi_gpio_6_6 || ORIG_REF_NAME==kyberBD_axi_gpio_6_6} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_auto_pc_0/kyberBD_auto_pc_0_ooc.xdc

# XDC: bd/kyberBD/ip/kyberBD_auto_pc_1_1/kyberBD_auto_pc_1_ooc.xdc

# XDC: bd/kyberBD/kyberBD_ooc.xdc
