# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/kyberBD/kyberBD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD || ORIG_REF_NAME==kyberBD} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_processing_system7_0_0/kyberBD_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_processing_system7_0_0 || ORIG_REF_NAME==kyberBD_processing_system7_0_0} -quiet] -quiet

# IP: bd/kyberBD/ip/kyberBD_proc_sys_reset_0_0/kyberBD_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kyberBD_proc_sys_reset_0_0 || ORIG_REF_NAME==kyberBD_proc_sys_reset_0_0} -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_processing_system7_0_0/kyberBD_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_processing_system7_0_0 || ORIG_REF_NAME==kyberBD_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_proc_sys_reset_0_0/kyberBD_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_proc_sys_reset_0_0 || ORIG_REF_NAME==kyberBD_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_proc_sys_reset_0_0/kyberBD_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kyberBD_proc_sys_reset_0_0 || ORIG_REF_NAME==kyberBD_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/kyberBD/ip/kyberBD_proc_sys_reset_0_0/kyberBD_proc_sys_reset_0_0_ooc.xdc

# XDC: bd/kyberBD/kyberBD_ooc.xdc
